import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/provider";

const inter = Inter({
    subsets:['latin'],
    variable:'--font-sans'
});

const plexMono = IBM_Plex_Mono({
    variable: "--font-plex-mono",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Polaris",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
        suppressHydrationWarning
        lang="en"
        className={cn("h-full", "antialiased", inter.variable, plexMono.variable, "font-sans")}
        >
            <body className="min-h-full flex flex-col">
                <Providers>
                    {children}
                    <Toaster/>
                </Providers>
            </body>
        </html>
    );
}